
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-logging-opsgy-com-v1beta1-lokirule
  failurePolicy: Fail
  name: vlokirule.kb.io
  rules:
  - apiGroups:
    - logging.opsgy.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lokirules
  sideEffects: None
